@@ .. @@
 const styles = StyleSheet.create({
   page: {
     padding: 30,
     fontSize: 12,
-    fontFamily: 'Helvetica',
+    fontFamily: 'Helvetica'
   },
   header: {
     marginBottom: 20,
     borderBottom: 1,
     paddingBottom: 10,
     borderBottomColor: '#2F5E1E',
   },
   headerContent: {
     flexDirection: 'row',
     justifyContent: 'space-between',
     alignItems: 'center',
     marginBottom: 10,
   },
   cooperativeInfo: {
     flex: 1,
   },
   cooperativeName: {
     fontSize: 16,
-    fontWeight: 'bold',
+    fontWeight: '700',
     marginBottom: 5,
     color: '#2F5E1E',
   },
   cooperativeLocation: {
     fontSize: 10,
     color: '#666',
   },
   title: {
     fontSize: 18,
     marginBottom: 10,
     textAlign: 'center',
     color: '#333',
   },
   subtitle: {
     fontSize: 12,
     textAlign: 'center',
     color: '#444',
   },
   section: {
     marginBottom: 15,
   },
   sectionTitle: {
     fontSize: 14,
-    fontWeight: 'bold',
+    fontWeight: '700',
     marginBottom: 5,
     backgroundColor: '#f3f4f6',
     padding: 5,
     borderLeftWidth: 4,
     borderLeftColor: '#2F5E1E',
     borderLeftStyle: 'solid',
   },
   routeInfo: {
     marginBottom: 15,
   },
   routeInfoRow: {
     flexDirection: 'row',
     marginBottom: 5,
   },
   routeInfoLabel: {
     width: '30%',
-    fontWeight: 'bold',
+    fontWeight: '700',
     color: '#444',
   },
   routeInfoValue: {
     width: '70%',
     color: '#333',
   },
   participantsSection: {
     marginBottom: 15,
   },
   participantRow: {
     flexDirection: 'row',
     marginBottom: 3,
   },
   participantLabel: {
     width: '30%',
-    fontWeight: 'bold',
+    fontWeight: '700',
     color: '#444',
   },
   participantValue: {
     width: '70%',
     color: '#333',
   },
   collectionTable: {
     marginTop: 10,
     marginBottom: 20,
   },
   tableHeader: {
     flexDirection: 'row',
     borderBottomWidth: 1,
     borderBottomColor: '#E5E7EB',
     backgroundColor: '#f3f4f6',
     padding: 5,
-    fontWeight: 'bold',
+    fontWeight: '700',
   },
   tableRow: {
     flexDirection: 'row',
     borderBottomWidth: 1,
     borderBottomColor: '#E5E7EB',
     padding: 5,
     minHeight: 40,
   },
   checkboxCell: {
     width: '5%',
     borderWidth: 1,
     borderColor: '#E5E7EB',
     height: 15,
     marginTop: 3,
   },
   producerCell: {
     width: '25%',
   },
   quantityCell: {
     width: '15%',
     borderBottomWidth: 1,
     borderBottomColor: '#E5E7EB',
     marginRight: 5,
   },
   weightCell: {
     width: '15%',
     borderBottomWidth: 1,
     borderBottomColor: '#E5E7EB',
     marginRight: 5,
   },
   timeCell: {
     width: '15%',
     borderBottomWidth: 1,
     borderBottomColor: '#E5E7EB',
     marginRight: 5,
   },
   phoneCell: {
     width: '15%',
   },
   signatureCell: {
     width: '10%',
     borderBottomWidth: 1,
     borderBottomColor: '#E5E7EB',
   },
   fuelSection: {
     marginTop: 15,
     marginBottom: 15,
   },
   fuelRow: {
     flexDirection: 'row',
     marginBottom: 5,
   },
   fuelLabel: {
     width: '50%',
-    fontWeight: 'bold',
+    fontWeight: '700',
     color: '#444',
   },
   fuelValue: {
     width: '50%',
     borderBottomWidth: 1,
     borderBottomColor: '#E5E7EB',
     height: 18,
   },
   notesSection: {
     marginTop: 15,
     marginBottom: 15,
   },
   notesBox: {
     borderWidth: 1,
     borderColor: '#E5E7EB',
     height: 100,
     marginTop: 5,
   },
   expensesSection: {
     marginTop: 15,
     marginBottom: 15,
   },
   expenseRow: {
     flexDirection: 'row',
     marginBottom: 5,
   },
   expenseLabel: {
     width: '30%',
-    fontWeight: 'bold',
+    fontWeight: '700',
     color: '#444',
   },
   expenseValue: {
     width: '70%',
     borderBottomWidth: 1,
     borderBottomColor: '#E5E7EB',
     height: 18,
   },
   paymentSection: {
     marginTop: 15,
   },
   paymentRow: {
     flexDirection: 'row',
     marginBottom: 10,
   },
   paymentLabel: {
     width: '50%',
     color: '#444',
   },
   paymentCheckbox: {
     width: 15,
     height: 15,
     borderWidth: 1,
     borderColor: '#E5E7EB',
     marginRight: 5,
   },
   paymentMethod: {
     flexDirection: 'row',
     alignItems: 'center',
   },
   accountField: {
     borderBottomWidth: 1,
     borderBottomColor: '#E5E7EB',
     flex: 1,
     marginLeft: 5,
     height: 18,
   },
   footer: {
     position: 'absolute',
     bottom: 30,
     left: 30,
     right: 30,
     textAlign: 'center',
     color: '#9ca3af',
     fontSize: 9,
     borderTopWidth: 1,
     borderTopColor: '#e5e7eb',
     borderTopStyle: 'solid',
     paddingTop: 10,
   },
   map: {
     width: '100%',
     height: 200,
     marginVertical: 10,
     border: 1,
     borderColor: '#E5E7EB',
   },
   producerForm: {
     marginBottom: 15,
     padding: 10,
     borderWidth: 1,
     borderColor: '#E5E7EB',
     borderRadius: 4,
   },
   producerFormHeader: {
     flexDirection: 'row',
     justifyContent: 'space-between',
     marginBottom: 8,
     borderBottomWidth: 1,
     borderBottomColor: '#E5E7EB',
     paddingBottom: 5,
   },
   producerFormName: {
-    fontWeight: 'bold',
+    fontWeight: '700',
     fontSize: 12,
   },
   producerFormPhone: {
     fontSize: 10,
     color: '#666',
   },
   producerSectionHeader: {
     flexDirection: 'row',
     justifyContent: 'space-between',
     marginBottom: 8,
   },
   formRow: {
     flexDirection: 'row',
     marginBottom: 6,
     alignItems: 'center',
   },
   producerSectionName: {
-    fontWeight: 'bold',
+    fontWeight: '700',
     fontSize: 12,
     alignItems: 'center',
   },
   formLabel: {
     width: '40%',
     fontSize: 10,
     color: '#555',
   },
   producerSectionPhone: {
     fontSize: 10,
     color: '#555',
   },
   formField: {
     width: '60%',
     height: 18,
     borderBottomWidth: 1,
     borderBottomStyle: 'dotted',
     borderBottomColor: '#999',
   },
   paymentOptions: {
     flexDirection: 'row',
     marginTop: 8,
     marginBottom: 8,
   },
   paymentOption: {
     flexDirection: 'row',
     alignItems: 'center',
     marginRight: 15,
   },
   paymentOptionLabel: {
     fontSize: 9,
     marginLeft: 3,
   },
   signatureArea: {
     flexDirection: 'row',
     justifyContent: 'space-between',
     marginTop: 10,
   },
   signatureBox: {
     width: '45%',
     height: 40,
     borderWidth: 1,
     borderColor: '#E5E7EB',
   },
   signatureLabel: {
     fontSize: 8,
     textAlign: 'center',
     marginTop: 3,
     color: '#666',
   },
   pageBreak: {
     height: 1,
     marginTop: 10,
     marginBottom: 10,
     backgroundColor: 'transparent',
     breakAfter: 'page',
   },
 });